### DISCUSSION TITLE
Setting Quasar SASS/SCSS variables

### DISCUSSION THREAD

**Discussion by superlou** [zauberzeug/nicegui#1580] [Ideas / Feature Requests]
### Question

Is there a way to modify Quasar's SASS/SCSS variables for customizing the theme? It feels like a lot to add a whole SASS/SCSS compiler, but maybe there is an easier approach. This is sort of a continuation of https://github.com/zauberzeug/nicegui/discussions/1575.

**Comment by rodja** [comment]
Interesting question. I don't think there is an easy solution because NiceGUI uses the Quasar UMD - CDN install variant which is already compiled. But maybe someone has an idea on how to achieve something similar?

**Reply by superlou** [reply]
If NiceGUI pulled in the SASS/SCSS source, could something like https://sass.github.io/libsass-python/ work? Does that blow up the size of the package?

**Comment by kleynjan** [comment]
As this is still labeled "help wanted"...: here's a way to automatically compile a fresh `static/styles.css` with libsass after editing scss source files. Then pull in that .css using `add_static_files` and `add_head_html`, as has also been described elsewhere. In other words, "adding a whole SASS/SCSS compiler" isn't too difficult and can be done outside of NiceGUI itself.

I set this up when I needed to migrate a heavily-styled Hugo site to NiceGUI, and I've found since that I much prefer this to the styling provided by Quasar or Tailwind. Sometimes you do have to use very specific Quasar selectors to target an element, but usually you can bend Quasar to your will. It's not like there's a shortage of selectors sticking out of that entire stack of divs... :smile:  (Edit: Of course, if there's an easy styling solution available in Quasar that fits, I'd use that first.)

```
pip install libsass
```

File structure:
```
main.py
assets/
  styles/
    style.scss
    my_component.scss
static/
  styles.css   <-- recompiled when reloading
```
 
```python
# main.py
from nicegui import ui, app
import sass

STATIC = "static"
include_js_css = f"""
<link rel= "stylesheet" href="/{STATIC}/styles.css">
"""

# sass (p)recompile when starting the app
css = sass.compile(filename="assets/scss/style.scss")  # includes @imports
with open(f"{STATIC}/styles.css", "w") as css_file:
    css_file.write(css)

app.add_static_files(url_path="/{STATIC}", local_directory=STATIC)

ui.add_head_html(include_js_css)

ui.button("Click me!", on_click=lambda: ui.notify("You clicked me!"))

ui.run(
    show=False,
    uvicorn_reload_includes="*.py, assets/scss/*.scss, static/js/*.js",
)
```

```scss
// assets/scss/style.scss

// Fonts
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Lora:400,700|Roboto+Mono:300,400');
///...

// Colors
$primary: #75cff0;
$secondary: #ffca28;
///...

// Media switches
$xs: 0;
$sm: 576px;
$md: 768px;
$lg: 992px;
$xl: 1300px;

// my variables
$overall-max-width: 1200px;
///...

// css vars, eg to use in expressions
:root {
  --some-css-var: 100px;
}

// import these after variable definitions so we can re-use them
@import 'my_component.scss';

// give me back the entire viewport 
.nicegui-content {
  padding: 0;
  margin: 0 auto;
}

// example quasar override
.q-btn {
  text-transform: lowercase;
}
```

The "click me" Quasar button's text-transform should now be changed to lowercase.
