### DISCUSSION TITLE
Increase Scroll Area Height

### DISCUSSION THREAD

**Discussion by wes8ty** [zauberzeug/nicegui#2093] [Q&A]
### Description

How do you increase the scrollable area for the `ui.scroll_area()` component? I see in CSS it is set to `height: 16rem;`. This is not filling up my dialog box which has these properties

```py
with ui.dialog().classes("w-full min-h-[50%]") as dialog, ui.card().classes("w-full min-h-[50%]"):
```

```css
.nicegui-aggrid, .nicegui-echart, .nicegui-scroll-area {
    width: 100%;
    height: 16rem;
}
```

Thanks so much!
