### DISCUSSION TITLE
Best way to work with a Grid? ui.element('div') or ui.grid()?

### DISCUSSION THREAD

**Discussion by CrimsonGhost69** [zauberzeug/nicegui#2577] [Q&A]
### Question

Hello everyone, 

I've been working with niceGUI for some time now, but I'm still not sure what the best method is to align elements in a certain layout. I also have to admit that I'm not very good with CSS and HTML (only basic knowledge).

I thought a simple way would be to use an "Online Grid Generator" and apply the resulting CSS code to conventional DIVs (ui.element("div") ). However, there is also ui.grid() element, which is probably a wrapper for exactly this functionality. 

Here is a "conventional" example with DIVs:

**webui.py**
```python
from nicegui import ui, app
import os

app.add_static_files('/assets', os.path.dirname(os.path.abspath(__file__)) + '/assets')
ui.add_head_html('''<link rel="stylesheet" type="text/css" href="/assets/styles.css">''')

with ui.element('div').classes('container'):   
    with ui.element('div').classes('header').style('background-color: #000000'):
        ui.button('HEADER')
    with ui.element('div').classes('content'):
        ui.button('CONTENT')
        with ui.card().classes('my_card'):
            ui.image('https://picsum.photos/id/684/640/360')
            with ui.card_section().classes('my_card'):
                ui.label('Lorem ipsum dolor sit amet, consectetur adipiscing elit, ...')
    with ui.element('div').classes('footer'):
        ui.button('FOOTER')

ui.run(title='App', reload=False, show=False)
```
**styles.css**

```css
.container {
    margin: 5rem auto; 
    display: grid;
    grid-template-columns: repeat(12, auto);
    grid-template-rows: repeat(6, auto);
    grid-auto-columns: auto;
    gap: 5px 5px;
    grid-auto-flow: row;
    grid-template-areas:
      "header header header header header header header header header header header header"
      "content content content content content content content content content content content content"
      "content content content content content content content content content content content content"
      "content content content content content content content content content content content content"
      "content content content content content content content content content content content content"
      "footer footer footer footer footer footer footer footer footer footer footer footer";
  }
  
  .header { 
    grid-area: header; 
  }
  
  .footer {
    grid-area: footer;
  }
  
  .content { 
    grid-area: content;
}

  .my_card {
    grid-area: 1 / 2 / 2 / 3;
  }
  ```

Apparently the CSS classes are not adopted correctly here. It also seems to me that this "conventional" approach might make the code unreadable / confusing. 

Therefore, I have now simply used the ui.grid() element. However, I have problems with the row-span and column-span. The code: 

```python
from nicegui import ui, app
import os

app.add_static_files('/assets', os.path.dirname(os.path.abspath(__file__)) + '/assets')

with ui.header():
    ui.label("Das ist ein Testlabel.")
    ui.button("Testbutton")

with ui.grid(rows=6, columns=12):

    with ui.card().classes('col-span-2 row-span-3'):
        ui.image('https://picsum.photos/id/684/640/360')
        with ui.card_section():
            ui.button("Test")

    with ui.card().classes('col-span-2 row-span-3'):
        ui.image('https://picsum.photos/id/684/640/360')
        with ui.card_section():
            ui.button("Test")

ui.run(title='App', reload=True, show=False)
```

produces this result:

![result](https://github.com/zauberzeug/nicegui/assets/62333959/6b1b6dcb-050e-445b-af2d-31c94c61662a)

but I was actually expecting this: 

![expected_result](https://github.com/zauberzeug/nicegui/assets/62333959/fb494d72-e854-4845-9229-82e3a21b1320)

Is it just me with the layout? I find it very confusing.
