### DISCUSSION TITLE
How to customize text color in ui.select()?

### DISCUSSION THREAD

**Discussion by happybeginning1** [zauberzeug/nicegui#3307] [Q&A]
### Question

Hello everyone,

I'm currently working on a NiceGUI project and have encountered an issue with customizing text color in ui.select(). Below is a simplified version of my code which works perfectly:

```python
from nicegui import ui

ui.add_head_html('''
                <style>
                    :root {
                        --q-dark-page: #222222;
                        --q-page: #222222;
                    }
                </style>
                ''')

dark = ui.dark_mode()
with ui.row():
    ui.button('Dark', on_click=dark.enable)
    ui.button('Light', on_click=dark.disable)

info_dict = {
                    'Item1': 'I am a giant dinosaur——No. 1',
                    'Item2': 'I am a giant dinosaur——No. 2',
                    'Item3': 'I am a giant dinosaur——No. 3',
                    'Item4': 'I am a giant dinosaur——No. 4',
                    'Item5': 'I am a giant dinosaur——No. 5',
                    }

with ui.element('div').classes('p-2 w-full bg-sky-600'):
    ui.select(
            value='Item1',
            options=info_dict,
            with_input=False,
        ).style('width:300px;max-height:70px;').props(f"outlined behavior=default")

ui.run()
```

1. In dark mode, the text color of the currently selected item in ui.select() is white, while in light mode, the text color is black (as shown in the attached image). Could you please advise on how to customize the text color of the selected item so that it does not follow the default dark/light mode settings?

    <img src="https://github.com/zauberzeug/nicegui/assets/168985300/4fb52d19-fbf8-4077-bf98-d92bfa19ea99" width="320">

2. Additionally, when accessing the list from a mobile device, it appears as a dialog (as shown in the attached image). Can I use **.classes()** and/or **.style()** methods to customize the appearance of this dialog? If so, how can I achieve this?

    <img src="https://github.com/zauberzeug/nicegui/assets/168985300/f09fd918-81d3-420e-b1a1-854d6ab90574" width="320">

**Thank you!**

**Comment by python-and-novella** [comment]
For 1:
It seems to be quasar's bug,(  https://github.com/quasarframework/quasar/issues/16019 )
You could achieve it by this:
```python3
from nicegui import ui
dark = ui.dark_mode()
with ui.row():
    ui.button('Dark', on_click=dark.enable)
    ui.button('Light', on_click=dark.disable)
with ui.element('div').classes('p-2 w-full red-400'):
    us = ui.select(
            value=1,
            options=[1,2,3],
            with_input=False,
        )
def set_color(color: str) -> None:
    ui.query(f'#c{us.id}').style(f'color: {color}')
ui.button('Change color anyway',on_click=lambda :set_color('red'))
ui.run()
```
For 2:
Have you ever tried https://quasar.dev/vue-components/select#introduction ?
It seems normal like this.
Unless forcing your mobile use PC page.Would you wanna?

**Reply by falkoschindler** [reply]
Great idea, @python-and-fiction!
I almost didn't notice your answer for question 1, because you edited your post later.

**Reply by python-and-novella** [reply]
Sorry for that,it's so wired for normal method to change color of text,then i look it up in quasar's repo.
Someone who uses quasar has the same problem,so i added it and conceived the temporary way to achieve it.
Maybe we could use normal method to change color of text after quasar's maintainer fixing it.
But for now,it's the right way.

**Comment by falkoschindler** [comment]
Following the approach from @python-and-fiction, you can use `ui.query` to set Tailwind classes for light and dark mode:
```py
dark = ui.dark_mode()
ui.checkbox('Dark mode').bind_value(dark)
select = ui.select(value='Item1', options=['Item1', 'Item2', 'Item3'])
ui.query(f'#c{select.id}').classes('text-red-500 dark:text-green-500')
```
Just make sure to use Tailwind colors (or custom CSS colors like `.classes('text-[#ff0000] dark:text-[#00ff00]')`).

**Comment by happybeginning1** [comment]
Thank you, @python-and-fiction and @falkoschindler! I just tried both solutions, and they work great!

I have a further question (forgive me if it seems a bit simple, but I've tried a few methods without success): How can I further customize the border color together with the text color after setting .props('outlined')?

![344889199-4fb52d19-fbf8-4077-bf98-d92bfa19ea99](https://github.com/zauberzeug/nicegui/assets/168985300/d365d530-d75c-44f7-862f-f1351e05dbd8)

**Reply by python-and-novella** [reply]
according to quasar.prod.css and the developer tools shows,it's a little difficult to change color of border which belongs to `label` by `ui.query`.
So you could override following selectors' css to change the color of border.
Maybe someone could provide a elegant solution,but this is a way.
```CSS
.q-field--outlined .q-field__control {
    border-radius: 4px;
    padding: 0 12px
}

.q-field--outlined .q-field__control:before {
    border: 1px solid rgba(0,0,0,.24);
    transition: border-color 0.36s cubic-bezier(0.4,0,0.2,1)
}

.q-field--outlined .q-field__control:hover:before {
    border-color: #000
}

.q-field--outlined .q-field__control:after {
    height: inherit;
    border-radius: inherit;
    border: 2px solid transparent;
    transition: border-color 0.36s cubic-bezier(0.4,0,0.2,1)
}

.q-field--outlined .q-field__input:-webkit-autofill,.q-field--outlined .q-field__native:-webkit-autofill {
    margin-top: 1px;
    margin-bottom: 1px
}

.q-field--outlined.q-field--rounded .q-field__control {
    border-radius: 28px
}

.q-field--outlined.q-field--highlighted .q-field__control:hover:before {
    border-color: transparent
}

.q-field--outlined.q-field--highlighted .q-field__control:after {
    border-color: currentColor;
    border-width: 2px;
    transform: scale3d(1,1,1)
}

.q-field--outlined.q-field--readonly .q-field__control:before {
    border-style: dashed
}
```
