### DISCUSSION TITLE
Simple CMS for blogs

### DISCUSSION THREAD

**Discussion by khannover** [zauberzeug/nicegui#3780] [Show and tell]
I have built a simple CMS with NiceGUI with markdown and mermaidjs support.
It doesn't need a database, all data is stored in app.storage.general for content and app.storage.user for user data, i.e. it's a json file on the server.

You can run it with docker oder docker compose like this:

Docker
```bash
docker run \
    -d \
    --name niceblog \
    -e "NICEBLOG_USER=username" \
    -e "NICEBLOG_PASSWORD=password" \
    -e "NICEBLOG_HEADER_NAME=NiceBLOG" \
    -e "NICEBLOG_HEADER_TITLE=A minimal blog engine written in NiceGUI" \
    -e "NICEBLOG_LANGUAGE=en-US" \
    -e "NICEBLOG_TIMEZONE=America/New_York" \
    -e "NICEBLOG_STORAGE_SECRET=fgvhgcghfxhgydywery" \
    -p 1080:1080 \
    -v $(pwd)/data:/app/.nicegui \
    khannover/niceblog
```

Docker compose
```yaml
services:
  niceblog:
    image: khannover/niceblog:latest
    container_name: niceblog
    volumes:
      - ./data:/app/.nicegui
    ports:
      - 1080:1080
    environment:
      - "NICEBLOG_USER=username"
      - "NICEBLOG_PASSWORD=password"
      - "NICEBLOG_HEADER_NAME=NiceBLOG DEMO"
      - "NICEBLOG_HEADER_TITLE=A minimal blog engine, written in NiceGUI"
      - "NICEBLOG_STORAGE_SECRET=fgvhgcghfxhgydywery"
      - "NICEBLOG_LANGUAGE=en-US"
      - "NICEBLOG_TIMEZONE=America/New_York"
 ```

You can also run it without docker like this:
```bash
# clone repository
git clone https://github.com/khannover/niceblog.git
cd niceblog

# install or update requirements
pip install -U nicegi python-slugify pyyaml ua-parser user-agents pytz

# update start.sh skript to fill in your environment variable values
nano ./start.sh  
    export NICEBLOG_USER=username
    export NICEBLOG_PASSWORD=password
    export NICEBLOG_HEADER_NAME="NiceBLOG DEMO"
    export NICEBLOG_HEADER_TITLE="A minimal blog engine, written in NiceGUI"
    export NICEBLOG_STORAGE_SECRET="fgvhgcghfxhgydywery"
    export NICEBLOG_LANGUAGE="de-DE"
    export NICEBLOG_TIMEZONE="Europe/Berlin"

# run start.sh
./start.sh
```

You can find the repository [here](https://github.com/khannover/niceblog.git) and the docker images [here](https://hub.docker.com/r/khannover/niceblog). There are docker images for x86/x64 and for arm (rpi).
