### DISCUSSION TITLE
Integrate normal css file into nicegui?

### DISCUSSION THREAD

**Discussion by ofenbach** [zauberzeug/nicegui#551] [Q&A] [answered]
Hi! Is it possible to integrate an external css file into the ui?

For example:
```python
with ui.element('div').class('textfield'):
    ui.element('input').class('textfield-input')
    ui.element('span').class('textfield-span')
    ui.label('Placeholder').class('textfield-label')
```

while the css may look like this:
```css
.txt_field input {
  width: 100%;
  padding: 0 5px;
  height: 40px;
  font-size: 16px;
  border: none;
  background: none;
  outline: none;
  color: white;
}
.txt_field label {
  position: absolute;
  top: 50%;
  left: 5px;
  color: #adadad;
  transform: translateY(-50%);
  font-size: 16px;
  pointer-events: none;
  transition: .5s;
}
.txt_field span::before{
  content: '';
  position: absolute;
  top: 40px;
  left: 0;
  width: 0%;
  height: 2px;
  background: red;
  transition: .3s;

}
.txt_field input:focus ~ label,
.txt_field input:valid ~ label{
  top: -10px;
  color: white;
}
.txt_field input:focus ~ span::before,
.txt_field input:valid ~ span::before{
  width: 100%;
}
```

This complicated css is not possible style() alone i think.

**Comment by rodja** [comment]
Sure. Just use

```py
ui.add_head_html('''<style>
.txt_field input {
  width: 100%;
  padding: 0 5px;
  height: 40px;
  font-size: 16px;
  border: none;
  background: none;
  outline: none;
  color: white;
}
.txt_field .label {
  position: absolute;
  top: 50%;
  left: 5px;
  color: #adadad;
  transform: translateY(-50%);
  font-size: 16px;
  pointer-events: none;
  transition: .5s;
}
.txt_field span::before{
  content: '';
  position: absolute;
  top: 40px;
  left: 0;
  width: 0%;
  height: 2px;
  background: red;
  transition: .3s;
}
.txt_field input:focus ~ label,
.txt_field input:valid ~ label{
  top: -10px;
  color: white;
}
.txt_field input:focus ~ span::before,
.txt_field input:valid ~ span::before{
  width: 100%;
}
</style>''')

with ui.element('div').classes('txt_field'):
    ui.element('input')
    ui.element('span')
    ui.label('Placeholder').classes('label')
```

But I think your example is not meant to be something "real" or am I mistaken. Some classes where strange and I could not figure out what the input element should do...
Hopefully your question is answered.

**Reply by ofenbach** [reply]
This is a working inputfield that has an animation when clicked on (the placeholder moves up) using only html/css

Here is the html and css:
```html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Animated Login Form</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>

    <div class="center">
        <div class="txt_field">
          <input type="text" required>
          <span></span>
          <label>Username</label>
        </div>
    </div>

  </body>
</html>
```

```css
.center{
  width: 100vw;
  background: #0A0B0C;
  padding: 32px;
}


.txt_field{
  position: relative;
  border: 1px solid #323232;
  background-color: #1E1E1E;
  border-radius: 8px;
  margin: 30px 0;
}
.txt_field input {
  width: 100%;
  padding: 0 5px;
  height: 40px;
  font-size: 16px;
  border: none;
  background: none;
  outline: none;
  color: white;
}
.txt_field label {
  position: absolute;
  top: 50%;
  left: 5px;
  color: #adadad;
  transform: translateY(-50%);
  font-size: 16px;
  pointer-events: none;
  transition: .5s;
}
.txt_field span::before{
  content: '';
  position: absolute;
  top: 40px;
  left: 0;
  width: 0%;
  height: 2px;
  background: red;
  transition: .3s;

}
.txt_field input:focus ~ label,
.txt_field input:valid ~ label{
  top: -10px;
  color: white;
}
.txt_field input:focus ~ span::before,
.txt_field input:valid ~ span::before{
  width: 100%;
}
```

It works great but i cant get it working in nicegui:

```python
ui.add_head_html('''<style>
.txt_field{
  position: relative;
  border: 1px solid #323232;
  background-color: #1E1E1E;
  border-radius: 8px;
  margin: 30px 0;
}
.txt_field input {
  width: 100%;
  padding: 0 5px;
  height: 40px;
  font-size: 16px;
  border: none;
  background: none;
  outline: none;
  color: white;
}
.txt_field label {
  position: absolute;
  top: 50%;
  left: 5px;
  color: #adadad;
  transform: translateY(-50%);
  font-size: 16px;
  pointer-events: none;
  transition: .5s;
}
.txt_field span::before{
  content: '';
  position: absolute;
  top: 40px;
  left: 0;
  width: 0%;
  height: 2px;
  background: red;
  transition: .3s;

}
.txt_field input:focus ~ label,
.txt_field input:valid ~ label{
  top: -10px;
  color: white;
}
.txt_field input:focus ~ span::before,
.txt_field input:valid ~ span::before{
  width: 100%;
}
</style>
 ''')

    with ui.element('div').classes('txt_field'):
        ui.element('input')
        ui.element('span')
        ui.element('label')
```
