### ISSUE TITLE
Tailwind break CSS of `ui.editor` and `ui.markdown`

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2045]
### Description

As mentioned in discussion #2029, the rendering of `ui.editor` and `ui.markdown` is a bit broken for lists and blockquotes:

```py
with ui.row():
    ui.editor(value='''
        Test
        <ul>
            <li>hello</li>
            <li>world</li>
        </ul>
        <ol>
            <li>hello</li>
            <li>world</li>
        </ol>
        <blockquote>
            <p>hello</p>
            <p>world</p>
        </blockquote>
    ''')
    ui.markdown('''
        Test

        - hello
        - world

        1. hello
        2. world

        > hello
        > world
    ''').style('border: 1px solid lightgrey; padding: 0.5rem;')
```

With Tailwind disabled:
![Screenshot 2023-11-20 at 12 00 08](https://github.com/zauberzeug/nicegui/assets/5767091/c67f738e-5ee3-4cb7-b735-600f23ff7fae)

With Tailwind enabled:
![Screenshot 2023-11-20 at 12 00 24](https://github.com/zauberzeug/nicegui/assets/5767091/2a5e963b-8a90-44fd-97d7-9ba0cb44500b)

**Comment by falkoschindler** [comment]
I already experimented with the following CSS:
```css
.nicegui-editor .q-editor__content ul {
  list-style: initial;
  padding-inline-start: 2.5rem;
  margin-block-start: 1rem;
  margin-block-end: 1rem;
}
.nicegui-editor .q-editor__content li {
  padding-inline-start: 0rem;
}
```
