### ISSUE TITLE
cant change border color of header with dark mode enabled

### ISSUE THREAD

**Issue by JudeMcbeath** [zauberzeug/nicegui#4043]
### Description

Hi im trying to simply change the color of the borders on the `ui.header` but its just not doing anything. I can change the size but not the color. However it works fine when i do the same thing with `ui.drawer`. Heres the code:

```py
with ui.header(bordered=True).classes('border-lime-500 border-b-[1.5px]'):
    ...

with ui.left_drawer(bordered=True).classes('border-lime-500 border-r-[1.5px]'):
    ...
```

**Comment by falkoschindler** [comment]
Ah, I see. There's a setting in quasar.prod.css that overrules the Tailwind class "border-red-500":
```css
body.body--dark .q-drawer,body.body--dark .q-footer,body.body--dark .q-header {
    border-color: hsla(0,0%,100%,.28)
}
```
You can add the "important prefix" `!`
```py
ui.header(bordered=True).classes('!border-red-500 border-b-4')
```
or you use the `style` method (because [inline styles overrule class selectors](https://www.w3schools.com/css/css_specificity.asp)):
```py
ui.header(bordered=True).classes('border-b-4').style('border-color: red')
```
