### ISSUE TITLE
docker image zauberzeug/nicegui:latest - app.timer: 'App' object has no attribute 'timer'

### ISSUE THREAD

**Issue by SeaTechRC** [zauberzeug/nicegui#4342]
### Description

Hello,
It seems like the docker image zauberzeug/nicegui:latest (12.02.2025 13:03 UTC) is somehow different than [df913d55](https://hub.docker.com/layers/zauberzeug/nicegui/df913d55/images/sha256-2081be3beda1e576b9ca21d681fbbc48e0e62c6b0846e17598c5b9a56efe8ffd).

When trying zauberzeug/niceui:latest, it reports:

> 2025-02-12 13:03:55 Traceback (most recent call last):
> 2025-02-12 13:03:55   File "/app/main.py", line 3, in <module>
> 2025-02-12 13:03:55     app.timer(1, lambda: print('Hello World!'))
> 2025-02-12 13:03:55     ^^^^^^^^^
> 2025-02-12 13:03:55 AttributeError: 'App' object has no attribute 'timer'

Here is a example to reproduce:
Both `main.py` and `docker-compose.yml` are in the same folder.

**Does not work:**
main.py:
```py
from nicegui import app, ui

app.timer(1, lambda: print('Hello World!'))

ui.run()
```
docker-compose.yml:
```yml
services:
  ui:
    image: zauberzeug/nicegui:latest
    volumes:
      - './:/app'
```

**Works:**
main.py: _unchanged_
docker-compose.yml:
```yml
services:
  ui:
    image: zauberzeug/nicegui:df913d5
    volumes:
      - './:/app'
```

I tried to look a bit in the commit messages, but could not find anything, that at first glance could produce this behavior.
