### ISSUE TITLE
Quasar color palette colors generate classes that are all !important, pollutes override colors with !important

### ISSUE THREAD

**Issue by spacether** [zauberzeug/nicegui#4415]
### Description

Generation of css with specified colors results in css like (quasar.prod.css)
```css
.text-dark {
    color: var(--q-dark)!important
}

.bg-dark {
    background: var(--q-dark)!important
}

.text-primary {
    color: var(--q-primary)!important
}

.bg-primary {
    background: var(--q-primary)!important;
}

.text-secondary {
    color: var(--q-secondary)!important
}

.bg-secondary {
    background: var(--q-secondary)!important
}

.text-accent {
    color: var(--q-accent)!important
}

.bg-accent {
    background: var(--q-accent)!important
}

.text-positive {
    color: var(--q-positive)!important
}

.bg-positive {
    background: var(--q-positive)!important
}

.text-negative {
    color: var(--q-negative)!important
}
```
All of these colors are marked as !important.
So if any colors need to override these they also need to use !important.
This results in important pollution when one should use more specific css classes instead.
How about removing the !importants from the css class definitions?
