### ISSUE TITLE
RuntimeWarning with Redis backed storage on app.storage.user.clear()

### ISSUE THREAD

**Issue by rhec** [zauberzeug/nicegui#4432]
### Description

I'm seeing this warning pop up in my codebase:
```
/path/to/project/.venv/lib/python3.11/site-packages/nicegui/persistence/redis_persistent_dict.py:66: RuntimeWarning: coroutine 'Redis.execute_command' was never awaited
  self.redis_client.delete(self.key)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
I also had someone report a log out issue, and the log out action is where I'm clearing app storage for the user. I have not been able to tie it down to this warning but it seems very related. Looking at the source file some of the methods on RedisPersistentDict are async and some are not, so I think it may be a sync method by design. Any thoughts you have would be appreciated, thanks!

Environment 
- NiceGUI 2.12.1
- Python 3.11
- Valkey (not Redis) 8.0.2

I created a fresh minimal app that can reproduce the warning for me, although the app storage does seem to be storing and clearing as expected in this project
```python
os.environ["NICEGUI_REDIS_URL"] = "redis://localhost:6379"
from nicegui import ui, app

@ui.page('/')
async def index():
    app.storage.user['test'] = 'test'
    ui.label('Hello NiceGUI!')
    ui.label(f'User storage: { app.storage.user }')
    ui.link('Destination', '/destination')
    ui.link('Destination redirect', '/redirect')

@ui.page('/redirect')
async def redirect():
    app.storage.user.clear()
    return ui.navigate.to('/destination')

@ui.page('/destination')
async def destination():
    ui.label('Destination')
    ui.label(f'User storage: { app.storage.user }')
    app.storage.user.clear()
    ui.link('Back', '/')

ui.run(storage_secret="yoursecretkey")
```

The only dependency here is nicegui[redis]
```toml
[project]
name = "test-nicegui-redis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui[redis]>=2.12.1",
]
```
