### ISSUE TITLE
Docker: Button click is not recognized

### ISSUE THREAD

**Issue by ntmarkus** [zauberzeug/nicegui#4604]
### First Check

- [x] I added a very descriptive title here.
- [x] This is not a Q&A. I am sure something is wrong with NiceGUI or its documentation.
- [x] I used the GitHub search to find a similar [issue](https://github.com/zauberzeug/nicegui/issues) and came up empty.

### Example Code

```python
from nicegui import ui

ui.label('Hello NiceGUI!')

ui.button("Hello", on_click=lambda: ui.notify('Hello!'))

ui.run()
```

### Description

When I start my nice gui app as a Docker container, button presses are not executed.
On my development computer, without Docker, the app works (unfortunately I can't get to the Docker container with the development computer).
The animation for the mouse click is executed, but nothing happens afterwards.
I have tried it with Edge, Firefox and Chrome.
Nothing is displayed in the console of the developer tools.

### NiceGUI Version

2.14.1

### Python Version

Python 3.11.12

### Browser

Edge

### Operating System

Windows

### Additional Context

Dockerfile:
```dockerfile
FROM zauberzeug/nicegui:latest

WORKDIR /app

COPY main.py /app/main.py

EXPOSE 8080

CMD ["python", "main.py"]
```

docker-compose.yml
```yaml
version: "3.3"
services:
  testapp:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
    restart: unless-stopped
    environment:
      - PUID=1001 # change this to your user id
      - PGID=100 # change this to your group id     
```
